import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const links = [
  { href: '/', label: 'Home', description: 'The homepage of the app.' },
  {
    href: '/docs',
    label: 'Docs',
    description: 'Find in-depth information about Next.js features and API.',
  },
  { href: '/todos', label: 'Todos', description: 'A simple todo app.' },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className="w-5/6 mx-auto flex items-center justify-center gap-4 mt-10 mb-32 text-center lg:max-w-5xl lg:w-full lg:mb-0 lg:grid-cols-4 lg:text-left">
              {links.map((link) => (
                <li
                  key={link.href}
                  className="group rounded-lg border border-transparent p-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
                >
                  <Link href={link.href}>
                    <p className="mb-3 text-2xl font-semibold">
                      {link.label}
                      <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
                        -&gt;
                      </span>
                    </p>
                    <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
                      {link.description}
                    </p>
                  </Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>

        {children}
      </body>
    </html>
  );
}
